/* Copyright (c) 2011 Danish Maritime Authority.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.maritimecloud.core.net;

import net.maritimecloud.core.message.Message;


/**
 * Abstract class for a message that can be broadcast.
 * <p>
 * Normally, there should be no need to manually extend this class. As subclasses of it are auto generated by MSDL
 * files.
 *
 * @author Kasper Nielsen
 */
public interface BroadcastMessage extends Message {

    // Object getService();// Or name???
    default String channel() {
        return getClass().getCanonicalName();
    }
}
