== MMS and Services
This chapter outlines how you can invoke and register services/endpoints using the Maritime Messaging Service. Since we use the word service in many situations with regards to the Maritime Cloud. We refer to services exposed via MMS as MMS endpoints or sometimes just endpoints. 

MMS endpoints are similar to web services. Basically an endpoint is just a method for communicating between two electronic devices over a network. Normally there is two parties involved in the exchange of data using a Web Service. A _Service Provider_ who *implements* a service that can be invoked by others. And a _Service Consumer_ who *uses* implementations provided by Service Providers. 

When using the Maritime Messaging Service things are a little bit different. Instead of the service provider communicating directly with the service consumer. The MMS serve acts as a relay between the two parties as described by this diagram:
["plantuml", "service-consumer-provider", "png"]
---------------------------------------------------------------------
participant "Service Consumer" as A
participant "MMS Server" as Server
participant "Service Provider" as B

A -> Server: invoke someEndpoint.abcd() at Client B
Server --> B: invoke someEndpoint.abcd()
B -> Server: return result of method to Client A
Server --> A: result
---------------------------------------------------------------------

=== Endpoint Definition
Normally, the definition of an endpoint is defined in a MSDL file. This file is then used to generate source code stubs that must be implemented by the party implementing the API of the endpoint. But for the following couple of examples we have already generated the stubs. So all you need to do use the following examples is to download the example jar and add it to your classpath. In later chapters we will see how you can write MSDL with your own endpoints.

The example jar available her http://repo1.maven.org/maven2/net/maritimecloud/examples/developer-guide/0.2/developer-guide-0.2.jar.

If you are using Maven (or a similar build system) you can use the following dependency:
[source,xml,subs="+attributes"]
----
<dependency>
    <groupId>net.maritimecloud.examples</groupId>
    <artifactId>developer-guide</artifactId>
    <version>{version}</version>
</dependency>
----

=== A simple example
In the following sections we will be using a very simple endpoint to demonstrate how endpoints can be used with the Maritime Messaging Service.

Our endpoint is very simple. It is just a single method that takes two integers and returns the sum of the two integers. Not something you would ever use a remote service for, but for demonstration purposes it will do just fine. Without going into detail about the syntax, here is the definition of the endpoint in MSDL.
[source]
----
namespace maritimecloud.examples;

endpoint MathEndpoint {
  /* Returns the sum of the two specified integer. */
  int sum(1:int left, 2:int right);
}
----
Endpoint definitions in MSDL are pretty similar to interface definitions in Java or C++ semantically wise. However the syntax is a bit different. 

The example jar you have downloaded already contains the stubs that was generated by MSDL code generator. For each endpoint two java stub files are generated. In this case an abstract class called _maritimecloud.examples.AbstractMathEndpoint_ which the service provider must extend. And an interface called _maritimecloud.examples.MathEndpoint_ which the service consumer uses to invoke methods on the remote endpoint.

==== Service Provider
Let us first look at the service provider who implements the functionality of the endpoint.

As previously mentioned we need to extend a class called AbstractMathEndpoint which was generated from a MSDL file. All methods of the endpoint are abstract methods that must be implemented. Besides the actual parameters to the endpoint. Each endpoint method also takes a _context_ object. This context can be used to query information about who is invoking the service. And what position there where at when invoking the service.

Our provider is really simple we just need to add two integers given. But in addition to the actual summation our implementation also prints out the two numbers and the id of the remote client that invoked the method. 

[source,java]
----
include::{sourcedir}/ch03services/MathEndpointImplementation.java[tag=code]
----

We also need to register the implementation with a MMS Server so remote clients can find and invoke methods on the endpoint.

Here is the full example of the Service Provider. For simplicity we have just embedded the actual endpoint implementation from the previous example as an anonymous class.  
[source,java]
----
include::{sourcedir}/ch03services/ServiceProvider.java[tag=code]
----

If you run the above code. Anyone connected to the same MMS server will now be able to use your service. The next section shows how to do this.

==== Service Consumer
To access a remote endpoint you must use an interface that is generated from a MSDL file.

In this case the maritimecloud.examples.MathEndpoint interface. Assuming we know the remote id of the service provider. Invoking the remote _sum_ method is very easy. Just make sure the service provider defined in the previous section is still running.
[source,java]
----
include::{sourcedir}/ch03services/ServiceConsumer.java[tag=code]
----

The example should be pretty self explanatory. However, the use of EndpointInvocationFuture might merit some explaining.

In our implementation of the Maritime Cloud every operation that might result in a network access is asynchronous.
That is the method/operation will return immediatly with a future that acts as a proxy for the result that is initially unknown.

In order to get the actual result of the operation you need to invoke _.join()_ on the returned future. The interface is really simple now. But in future versions this interface will be extended with additional operations for blocking and asynchronous completion.

=== Service Discovery
Sometimes we might not know the id of the service provider. For example, we want to find all service providers that provide a service in a certain area.

For example, the following code will find all actors that are within a 10 km radius exposing the MathEndpoint.
[source,java]
----
include::{sourcedir}/ch03services/FindService.java[tag=code]
----
All actors must have a registered PositionReader.













